### ISSUE TITLE
/s eth says crypto already added (it's not) and /f says „You don't have any coins in favorites.“

### ISSUE THREAD

**Issue by kettari** [darkodekan/crypto-telegram-bot#1]

**Comment by darkodekan** [comment]
Thanks for reporting the issue! I am deploying soon a new version of bot and we'll see if it resolves it. I'll notify you when it is deployed.

**Comment by darkodekan** [comment]
I just deployed the new version. Please test it and  let me know if the problem persists.

**Comment by darkodekan** [comment]
I noticed problem still persisted. Problem was that it was deleting favorites of other users, now all should be contained and isolated. I fixed it today and I will deploy the new version soon. It should work now. I'll notify you when it's done.

**Comment by kettari** [comment]
OK, please let me know when to check the bot.

**Comment by darkodekan** [comment]
> OK, please let me know when to check the bot.

I deployed the new version yesterday. Please let me know if it works. Thanks!

**Comment by kettari** [comment]
It works, thank you.
